[build]
  publish = "src/sentry/static/sentry/dist"
  command = "yarn webpack"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/client-config"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/api/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/sentry/dist/*"
  to = "/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "https://sentry.io/api/:splat"
  status = 200

[[redirects]]
  from = "/just/login"
  to = "https://sentry.io/auth/login/"
  status = 200
  headers = {Referer = "https://sentry.io/auth/login/"}


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
